# Pod for the log-creator app
apiVersion: v1
kind: Pod
metadata:
  name: log-creator-pod
  labels:
    app: log-creator
spec:
  containers:
    - name: log-creator
      image: jannisgz/log-creator:latest
      args: ["1.0"]
