apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pv-claim
spec:
  storageClassName: loki
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: log-pv-volume
